List<String> men2 = [
  't-shirt',
  'shirt',
  't-shirt',
  'coat 20%',
  'shirt',
  't-shirt',
  't-shirt 10%' ,
  't-shirt',
  't-shirt 30%',
  't-shirt',
  'shirt',
  't-shirt',
  'coat 20%',
  'shirt',
  't-shirt',
  't-shirt 10%' ,
  't-shirt',
  't-shirt 30%',
  't-shirt',
  'shirt',
  't-shirt',
  'coat 20%',
  'shirt',
  't-shirt',
  't-shirt 10%' ,
  't-shirt',
  't-shirt 30%',
];
List<String> women2 = [
  'dress 35%',
  'dress',
  'dress',
  'top',
  'skirt 30%',
  'dress',
  'baby dress',
  'baby dress',
  'baby 10%',
  'dress 35%',
  'dress',
  'dress',
  'top',
  'skirt 30%',
  'dress',
  'baby dress',
  'baby dress',
  'baby 10%',
  'dress 35%',
  'dress',
  'dress',
  'top',
  'skirt 30%',
  'dress',
  'baby dress',
  'baby dress',
  'baby 10%',
];

List<String> shoes2 = [
  'men shoes',
  'men shoes',
  'men shoes',
  'men shoes',
  'men shoes',
  'women heels',
  'men shoes',
  'man shoes 10%',
  'women shoes',
  'men shoes',
  'men shoes',
  'men shoes',
  'men shoes',
  'men shoes',
  'women heels',
  'men shoes',
  'man shoes 10%',
  'women shoes',
  'men shoes',
  'men shoes',
  'men shoes',
  'men shoes',
  'men shoes',
  'women heels',
  'men shoes',
  'man shoes 10%',
  'women shoes',
];

List<String> computer2 = [
  'desktop 10%',
  'desktop',
  'desktop',
  'desktop',
  'desktop',
  'desktop',
  'desktop 10%',
  'desktop',
  'desktop',
  'desktop',
  'desktop',
  'desktop',
  'desktop 10%',
  'desktop',
  'desktop',
  'desktop',
  'desktop',
  'desktop',
  'desktop 10%',
  'desktop',
  'desktop',
  'desktop',
  'desktop',
  'desktop',
];

List<String> laptop2 = [
  'hp laptop',
  'hp laptop',
  'hp laptop',
  'dell laptop',
  'dell laptop',
  'dell laptop',
  'asus laptop',
  'asus laptopr',
  'asus laptop',
  'hp laptop',
  'hp laptop',
  'hp laptop',
  'dell laptop',
  'dell laptop',
  'dell laptop',
  'asus laptop',
  'asus laptopr',
  'asus laptop',
  'hp laptop',
  'hp laptop',
  'hp laptop',
  'dell laptop',
  'dell laptop',
  'dell laptop',
  'asus laptop',
  'asus laptopr',
  'asus laptop',
];